const orderData = [
  {
    delivery_status: "Neworder",
    id: 5786,
    image_url: "/uploads/picture/image/541/All_Meal_Prep_Overnight_Oats.jpg",
    number: "35A59A",
    order_date: "Jan 30, 2024",
    order_time: "11:22 AM",
    paid_by: "Paid By User",
    total_price: "$222.80",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Delivered",
    id: 5785,
    image_url: "/uploads/picture/image/541/All_Meal_Prep_Overnight_Oats.jpg",
    number: "557C7B",
    order_date: "Jan 30, 2024",
    order_time: "11:17 AM",
    paid_by: "Paid By User",
    total_price: "$213.71",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Preparing",
    id: 5782,
    image_url: "/uploads/picture/image/541/All_Meal_Prep_Overnight_Oats.jpg",
    number: "8F8463",
    order_date: "Jan 30, 2024",
    order_time: "10:35 AM",
    paid_by: "Paid By User",
    total_price: "$213.71",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Canceled",
    id: 5781,
    image_url:
      "/uploads/picture/image/543/All_Meal_Prep_Bone_In_Thigh_with_Mashed_Potatoes.png",
    number: "F4CDB1",
    order_date: "Jan 30, 2024",
    order_time: "10:32 AM",
    paid_by: "Paid By User",
    total_price: "$225.90",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Neworder",
    id: 5780,
    image_url:
      "/uploads/picture/image/543/All_Meal_Prep_Bone_In_Thigh_with_Mashed_Potatoes.png",
    number: "F1496F",
    order_date: "Jan 30, 2024",
    order_time: "10:30 AM",
    paid_by: "Paid By User",
    total_price: "$225.90",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Canceled",
    id: 5779,
    image_url:
      "/uploads/picture/image/543/All_Meal_Prep_Bone_In_Thigh_with_Mashed_Potatoes.png",
    number: "0E266A",
    order_date: "Jan 30, 2024",
    order_time: "10:28 AM",
    paid_by: "Paid By User",
    total_price: "$225.90",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Neworder",
    id: 5778,
    image_url:
      "/uploads/picture/image/543/All_Meal_Prep_Bone_In_Thigh_with_Mashed_Potatoes.png",
    number: "4146F4",
    order_date: "Jan 30, 2024",
    order_time: "10:26 AM",
    paid_by: "Paid By User",
    total_price: "$225.90",
    user_name: "Euro billing Rondon",
  },
  {
    delivery_status: "Preparing",
    id: 5777,
    image_url:
      "/uploads/picture/image/543/All_Meal_Prep_Bone_In_Thigh_with_Mashed_Potatoes.png",
    number: "0BE844",
    order_date: "Jan 30, 2024",
    order_time: "10:24 AM",
    paid_by: "Paid By User",
    total_price: "$225.90",
    user_name: "Euro billing Rondon",
  },
  // Resto de los elementos con estados aleatorios
];

export default orderData;
